#### Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [13]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [14]:
iris=load_iris()

In [15]:
x=iris.data
y=iris.target

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
knnClassifier=KNeighborsClassifier(n_neighbors=5)

In [20]:
knnClassifier.fit(x_train,y_train)

KNeighborsClassifier()

In [21]:
y_pred=knnClassifier.predict(x_test)

In [22]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [23]:
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 1.0


#### Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [25]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [26]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [29]:
raw_df.head()

0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8

In [39]:
pd.DataFrame(data).isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [31]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [40]:
x=data
y=target

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
knn_regressor=KNeighborsRegressor(n_neighbors=5)

In [44]:
knn_regressor.fit(x_train,y_train)

KNeighborsRegressor()

In [45]:
y_pred=knn_regressor.predict(x_test)

In [46]:
y_pred

array([24.54, 29.34, 14.6 , 28.  , 16.74, 31.88, 19.74, 16.06, 18.02,
       21.18, 23.38, 20.04, 12.42, 21.34, 23.7 , 22.22, 19.04, 14.06,
       35.14, 10.6 , 25.86, 29.34, 16.78, 21.08, 18.88, 22.78, 22.46,
       11.46, 23.38, 21.94, 22.68, 23.44, 10.3 , 30.04, 17.54, 21.12,
       21.66, 25.98, 22.52, 28.  , 21.18, 30.46, 38.16, 22.4 , 24.84,
       12.6 , 19.46, 28.  , 19.8 , 21.56, 22.44, 34.7 , 17.96, 21.18,
       30.36, 21.38, 12.5 , 35.14, 21.74, 21.12, 25.3 , 38.82, 29.1 ,
       14.3 , 30.46, 23.38, 12.26, 25.3 , 35.04, 13.36, 20.58, 22.52,
       17.66, 25.3 , 22.46,  8.98, 19.68, 38.16, 10.94, 14.08, 22.88,
       15.96, 24.32, 12.24, 21.46, 31.98, 14.16, 21.66, 26.04, 17.86,
       22.98, 14.7 , 17.48, 20.36, 24.76, 17.86, 30.16,  8.7 , 10.76,
       11.92, 21.8 , 22.46])

In [48]:
from sklearn.metrics import mean_squared_error

In [50]:
print("Mean Squared Error",mean_squared_error(y_test,y_pred))

Mean Squared Error 25.860125490196076


#### Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [57]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score

In [54]:
iris=load_iris()

In [55]:
x=iris.data
y=iris.target

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [59]:
k_values=list(range(1,15))

In [60]:
mean_accuracy=[]
for k in k_values:
    knn=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn,x_train,y_train,cv=5)
    mean_accuracy.append(scores.mean())

In [63]:
optimal_k = k_values[mean_accuracy.index(max(mean_accuracy))]
print("Optimal K:", optimal_k)

Optimal K: 3


#### Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [66]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [67]:
x=data
y=target

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [69]:
scaller=StandardScaler()

In [74]:
x_train_scaled=scaller.fit_transform(x_train)
x_test_scaled=scaller.fit_transform(x_test)

In [76]:
knn=KNeighborsRegressor(n_neighbors=5)

In [77]:
knn.fit(x_train_scaled,y_train)

KNeighborsRegressor()

In [78]:
y_pred=knn.predict(x_test_scaled)

In [79]:
y_pred

array([25.84, 33.64, 17.72, 24.08, 16.98, 22.9 , 19.96, 16.92, 21.4 ,
       20.08, 24.02, 21.36, 11.9 , 25.26, 18.46, 21.86, 20.3 , 10.18,
       36.9 , 14.2 , 25.34, 27.36, 15.02, 21.18, 15.88, 16.66, 24.36,
       11.04, 21.42, 20.2 , 25.5 , 23.5 , 14.72, 21.88, 16.16, 19.08,
       32.26, 19.58, 23.8 , 24.58, 19.16, 30.86, 36.9 , 20.12, 26.72,
       13.52, 15.98, 25.06, 19.  , 33.76, 21.44, 36.24, 17.12, 23.44,
       42.44, 21.76, 16.54, 35.06, 25.42, 18.58, 26.5 , 33.7 , 32.08,
       21.54, 23.26, 21.48, 14.2 , 24.58, 32.06, 14.86, 20.14, 22.34,
       14.58, 20.94, 24.04,  8.06, 21.28, 36.9 , 11.54, 14.2 , 22.76,
       11.04, 22.6 , 11.02, 20.68, 27.5 , 14.94, 23.54, 26.48, 18.1 ,
       24.98, 10.28, 18.22, 21.3 , 26.96, 18.22, 20.  ,  9.78, 11.74,
       10.8 , 22.74, 25.54])

In [80]:
print("Mean Squared Error",mean_squared_error(y_test,y_pred))

Mean Squared Error 21.42554117647059


#### Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [81]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a KNN classifier object with weighted voting
knn = KNeighborsClassifier(n_neighbors=3, weights='distance')

# Train the classifier using the training data
knn.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = knn.predict(X_test)

# Print the predictions and corresponding true labels
print("Predictions:", y_pred)
print("True Labels:", y_test)


Predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
True Labels: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


#### Q6. Implement a function to standardise the features before applying KNN classifier.

In [82]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [83]:
from sklearn.preprocessing import StandardScaler

def standardize_features(X_train, X_test):
    scaler = StandardScaler()
    X_train_std = scaler.fit_transform(X_train)
    X_test_std = scaler.transform(X_test)
    return X_train_std, X_test_std


#### Q7. Write a Python function to calculate the euclidean distance between two points.

In [84]:
import math

def euclidean_distance(point1, point2):
    distance = 0
    for i in range(len(point1)):
        distance += (point1[i] - point2[i]) ** 2
    distance = math.sqrt(distance)
    return distance


In [85]:
point1 = [1, 2, 3]
point2 = [4, 5, 6]
distance = euclidean_distance(point1, point2)
print("Euclidean Distance:", distance)


Euclidean Distance: 5.196152422706632


#### Q8. Write a Python function to calculate the manhattan distance between two points.

In [86]:
def manhattan_distance(point1, point2):
    distance = sum(abs(a - b) for a, b in zip(point1, point2))
    return distance


In [87]:
point1 = [1, 2, 3]
point2 = [4, 5, 6]
distance = manhattan_distance(point1, point2)
print("Manhattan Distance:", distance)


Manhattan Distance: 9
